[package]
name = "wasm-bpf-libbpf-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.1"
thiserror = "1.0.40"
wasm-bpf-binding = { path = "../wasm-bpf-binding", version = "0.1.0" }
